full_rebuild: true
name: Ginger Docs
author: Brad Cypert
version: v1.1
encoding: utf-8
defaults:
  -
    values:
      layout: "index"
markdown: kramdown
kramdown:
  input: GFM
relative_permalinks: false
collections:
- entries
sass:
  sass_dir: _sass
  style: :compressed
exclude: [
.git,
.gitignore,
README.md,
.sass-cache
]
